### ISSUE TITLE
CSS compression is changing the order off lines of CSS

### ISSUE THREAD

**Issue by LushawnDev** [astro-community/astro-compress#125]
I was wondering if you have come across this behaviour before. I believe to have isolated my problem to the `astro-compress` integration.

When I run `astro build` in my project and the CSS compression takes place, the order of the lines of my CSS are being changed in the compression process. This is causing the incorrect styling to take precedence, namely in my media queries as the breakpoints are in the incorrect order to work (I am using `max-width` breakpoints so require them to descend in size in my CSS for them to work correctly).

If I set compression to false in my config as below, the issue goes away, which makes me believe it's the integration's CSS compression causing the issue
```
export default defineConfig({
  integrations: [
    compress({
      css: false,
    }),
  ],
});
```

My CSS and overall Astro setup is a bit complicated so it may be difficult for me to make a minimum reproducible repo, but I can try if very necessary.

I use SCSS everywhere in my project, which may be relevant. The styles that I noticed this was happening in are in my global sass files as opposed to component styling.

These styles are in my `/src/sass/` directory, where I have an abstracts and base directory with further sass files that all get imported into my `global.scss`. See image of directory below.

![image](https://github.com/astro-community/astro-compress/assets/63189446/62660b8c-6865-411c-87df-c7e18a742880)

I've disabled CSS compression for now, and happy to help investigate the issue where needed.

Thanks for the great integration so far!

**Comment by nikolaxhristov** [comment]
So, `astro-compress` uses `csso` under the hood for CSS compression, so you might want to check that out. https://www.npmjs.com/package/csso. In particular the `restructure` option. See if you can disable it first and then try again. Also you might try `forceMediaMerge` off.

```ts
import compress from "astro-compress";
import { defineConfig } from "astro/config";

export default defineConfig({
	integrations: [
		compress({
			css: {
				restructure: false,
				forceMediaMerge: false
			},
		}),
	],
});
```

Hope this helps!

**Comment by xanode** [comment]
Hello,

I've got the same problem in an Astro project.

I use the TailwindCSS integration and the typography plugin of this framework. When using media queries, for example like this:

```html
<body>
  <h1 class="text-3xl font-bold text-red-500 md:text-green-500 lg:text-black">
    Hello world!
  </h1>
  <div class="prose lg:prose-lg">
    <h1>Title</h1>
    <p>Text</p>
  </div>
</body>
```

We get media queries written in this order:

```css
@media (min-width: 1024px) {
  /* CSS related to lg:prose-lg */
}

@media (min-width: 768px) {
  .md\:text-green-500 {
    --tw-text-opacity: 1;
    color: rgb(34 197 94 / var(--tw-text-opacity));
  }
}

@media (min-width: 1024px) {
  .lg\:text-black {
    --tw-text-opacity: 1;
    color: rgb(0 0 0 / var(--tw-text-opacity));
  }
}
```

The use of `astro-compress` (and more specifically `csso`) gathers the media queries but does not correct the order which causes a distortion of the style :

```css
@media (min-width: 1024px) {
  /* CSS related to lg:prose-lg */
  .lg\:text-black {
    --tw-text-opacity: 1;
    color: rgb(0 0 0 / var(--tw-text-opacity));
  }
}

@media (min-width: 768px) {
  .md\:text-green-500 {
    --tw-text-opacity: 1;
    color: rgb(34 197 94 / var(--tw-text-opacity));
  }
}
```
Then we have medium-screen style overriding large-screen style on large screens.

Although this avoids duplication of code, it seems that it would be better to keep a specific order so as not to break this kind of thing (decreasing order when using `@media (max-width: ...` and increasing order for `@media (min-width: ...` for example).

We would have preferred this:
```css
@media (min-width: 768px) {
  .md\:text-green-500 {
    --tw-text-opacity: 1;
    color: rgb(34 197 94 / var(--tw-text-opacity));
  }
}

@media (min-width: 1024px) {
  /* CSS related to lg:prose-lg */
  .lg\:text-black {
    --tw-text-opacity: 1;
    color: rgb(0 0 0 / var(--tw-text-opacity));
  }
}
```

I think it is related to [this issue](https://github.com/css/csso/issues/424) of csso.
In this particular case setting `forceMediaMerge: false` is indeed a (partial?) fix.
